import { fetch } from 'popsicle'

// this is the full API, seperated for easy reference
// tier is Object.keys(info.region)[0] from login
// all calls except login use headers.TOKEN_AUTH & headers.ACCOUNT_ID (info.authtoken.authtoken, info.account.id from login)
// account id is headers.ACCOUNT_ID

export const client = {
  get: (url, options) => fetch(url, options).then(r => r.json()),
  post: (url, input, options) => fetch(url, { method: 'POST', ...options, body: JSON.stringify(input) }).then(r => r.json())
}

export const videos = (tier, accountID, since, page = 0, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${accountID}/media/changed?since=${since.toISOString()}&page=${page}`, options)
export const network = (tier, network, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}`, options)

export const accountOptions = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/account/options`, options)
export const acknowledgeNotification = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v2/notification`, input, options)
export const activateSiren = (tier, network, siren, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/${siren}/activate/`, input, options)
export const activateSirens = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/activate/`, input, options)
export const addCamera = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/add`, input, options)
export const addChime = (tier, account, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${account}/networks/${network}/chimes/add/`, input, options)
export const addSiren = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/add/`, input, options)
export const appUpdateStatus = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/version`, options)
export const armDisarmNetwork = (tier, network, type, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/${type}`, input, options)
export const batteryUsage = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/camera/usage`, options)
export const blinkStabilityStatus = (tier, options) => client.get(`https://blinkstatus.net/api/v1/${tier}`, options)
export const cameraCommandStatus = (tier, network, camera, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}`, options)
export const cameraMotion = (tier, network, camera, type, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/${type}`, input, options)
export const changePassword = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/account/change_password/`, input, options)
export const commandPolling = (tier, network, command, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}/command/${command}`, options)
export const contactBlink = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v2/support/ob_phone/`, options)
export const createProgram = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs/create`, input, options)
export const createSystem = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/add`, input, options)
export const deactivateSirens = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/deactivate/`, input, options)
export const deleteAccount = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/account/delete/`, input, options)
export const deleteCamera = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/delete/`, input, options)
export const deleteMedia = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/{accountId}/media/delete`, input, options)
export const deleteMediaCall = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/{accountId}/media/delete`, input, options)
export const deleteProgram = (tier, network, program, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs/${program}/delete`, input, options)
export const deleteSirens = (tier, network, siren, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/${siren}/delete`, input, options)
export const deleteSyncModule = (tier, network, syncmodule, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/syncmodule/${syncmodule}/delete/`, input, options)
export const deleteSystem = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/delete`, input, options)
export const disableProgram = (tier, network, program, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs/${program}/disable`, input, options)
export const downloadFirmwareUpdate = (tier, serial, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/sync_modules/${serial}/fw_update`, options)
export const enableProgram = (tier, network, program, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs/${program}/enable`, input, options)
export const getAccount = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/account`, options)
export const getCameraConfig = (tier, network, camera, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/config`, options)
export const getChangedMedia = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/{accountId}/media/changed`, options)
export const getChangedVideos = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v2/videos/changed`, options)
export const getClientOptions = (tier, account, client, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${account}/clients/${client}/options`, options)
export const getMotionRegions = (tier, account, network, camera, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${account}/networks/${network}/cameras/${camera}/motion_regions`, options)
export const getPrograms = (tier, network, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs`, options)
export const getRegions = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/regions`, options)
export const getSirens = (tier, network, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/`, options)
export const getSirensForAllNetworks = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/sirens/`, options)
export const getUser = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/user`, options)
export const homescreenV3 = (tier, account, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v3/accounts/${account}/homescreen`, options)
export const liveView = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v3/networks/${network}/cameras/${camera}/liveview`, input, options)
export const liveViewV5 = (tier, account, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v5/accounts/${account}/networks/${network}/cameras/${camera}/liveview`, input, options)
export const loadCameraSettings = (tier, network, camera, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/config`, options)
export const loadCameraStatus = (tier, network, camera, options) => client.get(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/signals`, options)
export const login = (input, options) => client.post('https://rest.prod.immedia-semi.com/login', input, options)
export const logout = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/logout/`, input, options)
export const refreshCameraStatus = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/status`, input, options)
export const regions = (options) => client.get('https://rest-prod.immedia-semi.com/regions', options)
export const register = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v2/account/register`, input, options)
export const resetPassword = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/account/reset_password/`, input, options)
export const saveCalibrateTemperature = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/network/${network}/camera/${camera}/calibrate`, input, options)
export const saveCameraSettings = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/update`, input, options)
export const sendClientOptions = (tier, account, client, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${account}/clients/${client}/options`, input, options)
export const sendLogs = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/app/logs/upload/`, input, options)
export const sendLogsCall = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/app/logs/upload/`, input, options)
export const sendSystemOfflineHelpEmail = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/account/system_offline/${network}`, input, options)
export const setMotionRegions = (tier, account, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/accounts/${account}/networks/${network}/cameras/${camera}/motion_regions`, input, options)
export const startOnboarding = (tier, network, type, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v2/network/${network}/sync_module/${type}`, input, options)
export const takeSnapshot = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/camera/${camera}/thumbnail`, input, options)
export const tempAlertDisable = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/network/${network}/camera/${camera}/temp_alert_disable`, input, options)
export const tempAlertEnable = (tier, network, camera, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/network/${network}/camera/${camera}/temp_alert_enable`, input, options)
export const terminateCommand = (tier, network, command, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/command/${command}/done/`, input, options)
export const terminateOnboardingCommand = (tier, network, command, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/command/${command}/update/`, input, options)
export const updateAccount = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/account/update`, input, options)
export const updateCheck = (tier, options) => client.get(`https://rest-${tier}.immedia-semi.com/api/v1/fw/app/update_check`, options)
export const updateCommand = (tier, network, command, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/command/${command}/update/`, input, options)
export const updateCommandSync = (tier, network, command, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/command/${command}/update/`, input, options)
export const updateNetworkSaveAllLiveViews = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/update`, input, options)
export const updateProgram = (tier, network, program, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/programs/${program}/update`, input, options)
export const updateSiren = (tier, network, siren, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/${siren}/update`, input, options)
export const updateSirens = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/networks/${network}/sirens/update`, input, options)
export const updateSystem = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/update`, input, options)
export const updateTimezone = (tier, network, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/network/${network}/update`, input, options)
export const verificationEmail = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/account/resend_verification/`, input, options)
export const videoOptionsSetter = (tier, input, options) => client.post(`https://rest-${tier}.immedia-semi.com/api/v1/account/video_options`, input, options)
